version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-md04
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: redis-md04
    ports:
      - "6379:6379"
